### ISSUE TITLE
Merge important work from dunai

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/simple-affine-space#1]
@turion included definitions in https://github.com/ivanperez-keera/dunai that overlap with this work.

We could merge everything into one library and, that way, both Yampa and dunai can depend on it.

**Comment by turion** [comment]
Yes. Do you mean all the different `VectorSpace` instances? If yes, I'll send a PR containing:

* Tuple instances
* Num/Fractional (?) newtype instances
* Instances for typical builtin types (Double, Float etc.)

------------------------

Side note: I originally even started to work on this here: https://github.com/turion/vector-space-light/blob/master/vector-space.cabal
I still have unpushed changes somewhere, but I guess those aren't needed anymore.
