### ISSUE TITLE
Delete unneeded language extension

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/simple-affine-space#10]
In order to partially fix https://github.com/commercialhaskell/stackage/issues/5110, it would be cool to delete the language extensions `MultiParamTypeClasses`, which are implied by `FunctionalDependencies`. It would be great to release a new version eventually, so I can make progress with stackage integration.

**Comment by ivanperez-keera** [comment]
The new release and the modification would be different issues, so I have edited the title for this one.
