### ISSUE TITLE
I'm stackage maintainer for this package

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/simple-affine-space#8]
As of https://github.com/commercialhaskell/stackage/commit/490e5f55c294fcb7376a5140217645eadb571449, I'm stackage maintainer for `simple-affine-space`.

I think I didn't explicitly ask for it, but it became necessary after `dunai-0.6` (which is on `stackage`) has this as a dependency.

**Comment by ivanperez-keera** [comment]
Got it!
